data:
  train_dir: "/content/drive/MyDrive/Bio_Data/biological_data_pfp/train"
  test_dir:  "/content/drive/MyDrive/Bio_Data/biological_data_pfp/test"

  out_dir:  "/Users/anahitasoltantoyeh/Desktop/Project/output"

model:
  subset_n: 2000         # set null to use all
  val_frac: 0.1
  random_state: 42
  max_iter: 200

blast:
  enabled: true
  evalue_thresh: 0.001
  topk: 50
  alpha: 0.2              # final = alpha*ML + (1-alpha)*BLAST

predict:
  topk_per_aspect: 500    # cap per aspect
  min_score: 1.0e-6
